export const games = [
    {
      id: 1,
      title: "Grand Theft Auto 5",
      url: "https://hips.hearstapps.com/digitalspyuk.cdnds.net/13/14/gaming-gta5-cover.jpeg?resize=480:*",
      originalPrice: 49.95,
      salePrice: 14.95,
      rating: 5,
    },
    {
      id: 2,
      title: "Call of duty Blacks Ops 2",
      url: "https://m.media-amazon.com/images/M/MV5BMjBiMjhmNWItNmU0OS00MWZkLTgzMTItMDcxN2RjYmZmNWJmXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg",
      originalPrice: 39,
      salePrice: null,
      rating: 5,
    },
    {
      id: 3,
      title: "Fortnite",
      url: "https://m.media-amazon.com/images/M/MV5BNzU2YTY2OTgtZGZjZi00MTAyLThlYjUtMWM5ZmYzOGEyOWJhXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg",
      originalPrice: 29,
      salePrice: null,
      rating: 5,
    },
    {
      id: 4,
      title: "Ratchet and Clank",
      url: "https://m.media-amazon.com/images/I/81AXAxrbb-L._AC_SL1500_.jpg",
      originalPrice: 44,
      salePrice: 19,
      rating: 4.5,
    },
    {
      id: 5,
      title: "Minecraft",
      url: "https://upload.wikimedia.org/wikinews/en/7/7a/Minecraft_game_cover.jpeg",
      originalPrice: 32,
      salePrice: null,
      rating: 5,
    },
    {
      id: 6,
      title: "Apex Legends",
      url: "https://m.media-amazon.com/images/M/MV5BOTlhMTdiY2YtOTI3My00Y2M5LWI5YWQtYzgyYzgzMzhlMzExXkEyXkFqcGdeQXVyMzM2MzI5MzU@._V1_UY1200_CR135,0,630,1200_AL_.jpg",
      originalPrice: 70,
      salePrice: 12.5,
      rating: 4.5,
    },
    {
      id: 7,
      title: "Roblox",
      url: "https://i.harperapps.com/covers/9780062862600/y648.jpg",
      originalPrice: 11,
      salePrice: 10,
      rating: 4,
    },
    {
      id: 8,
      title: "Forza Horizon 5",
      url: "https://store-images.s-microsoft.com/image/apps.7859.14506879174941978.138d3eab-0b06-443b-a252-c99592521394.33a348aa-892d-49b8-9ef2-6ff06c22cf96",
      originalPrice: 38,
      salePrice: 17.95,
      rating: 4.5,
    },
    {
      id: 9,
      title: "Rocket League",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Rocket_League_coverart.jpg/768px-Rocket_League_coverart.jpg",
      originalPrice: 35,
      salePrice: 19.95,
      rating: 4.5,
    },
    {
      id: 10,
      title: "Valorant",
      url: "https://s2.gaming-cdn.com/images/products/6568/orig-fallback-v1/valorant-pc-game-steam-cover.jpg?v=1646313124",
      originalPrice: 40,
      salePrice: null,
      rating: 5,
    },
    {
      id: 11,
      title: "League of Legends",
      url: "https://interfaceingame.com/wp-content/uploads/league-of-legends/league-of-legends-cover-375x500.jpg",
      originalPrice: 30,
      salePrice: 20,
      rating: 5,
    },
    {
      id: 12,
      title: "Fifa 22",
      url: "https://i5.walmartimages.ca/images/Enlarge/188/438/6000204188438.jpg",
      originalPrice: 30,
      salePrice: 12.95,
      rating: 2.0,
    },
  ];